# Generated by Django 6.0.3 on 2026-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
