# Generated by Django 6.0.3 on 2026-05-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_produit_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenu',
        ),
    ]
