# Generated by Django 6.0.3 on 2026-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0004_delete_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('caramelle', 'Caramelle'), ('fraise', 'Fraise'), ('kiwi', 'Kiwi'), ('tarte', 'Tarte'), ('croissante', 'Croissante')], default='chocolate', max_length=20),
        ),
    ]
