# Generated by Django 6.0.5 on 2026-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0005_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV'), ('sport', 'Sportive'), ('electrique', 'Électrique'), ('luxe', 'Luxe'), ('crossover', 'Crossover')], default='berline', max_length=20),
        ),
    ]
